### ISSUE TITLE
피드 스크린에서 사용될 바텀 시트 컴포넌트 구현

### ISSUE THREAD

**Issue by Choisehyeon** [Grusie/SharingMap#15]
## 📝 요약
기능 요청에 대한 간략한 설명을 작성해주세요.

## 💡 Todo
- [x] 바텀 시트 컴포넌트 구현
- [x] 아카이빙 리스트 아이템 컴포넌트 구현
- [x] 댓글 아이템 컴포넌트 구현

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
