### ISSUE TITLE
text 길이에 따른 더보기, 접기 기능 구현

### ISSUE THREAD

**Issue by Choisehyeon** [Grusie/SharingMap#32]
## 📝 요약
text 길이에 따른 더보기, 접기 기능 구현

## 💡 Todo
- [x] 더보기 클릭 전체 텍스트가 다 보이도록 구현
- [x] 전체 텍스트가 보이면 접기 텍스트도 같이 보일 수 있도록 구현
- [x] 접기 클릭시 이전 텍스트가 보였던 방식으로 돌아가도록 구현

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
