### ISSUE TITLE
User 스크린 구현

### ISSUE THREAD

**Issue by Choisehyeon** [Grusie/SharingMap#33]
## 📝 요약
( 사용자가 아닌 다른 유저) User 스크린 구현

## 💡 Todo
- [x] 유저 정보 컴포넌트 붙이기
- [x] 피드 컴포넌트 붙이기
- [x] 보관함 컴포넌트 붙이기

## 🔗 관련 링크
이 기능 요청과 관련된 추가 링크가 있다면 여기에 작성해주세요.
